# Generated by Django 4.2.4 on 2023-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("usd_to_rub", models.DecimalField(decimal_places=4, max_digits=10)),
                ("eur_to_rub", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
